# Generated by Django 4.2.13 on 2024-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_update_admin_log_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('BUSINESS', 'Business')], default='CUSTOMER', max_length=20),
        ),
    ]
