# Generated by Django 4.2.13 on 2024-07-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bvn',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
