# Generated by Django 4.2.13 on 2024-07-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_business_tax_id_remove_customer_nin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state_of_origin',
            field=models.CharField(default='Lagos', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_of_residence',
            field=models.CharField(default='Lagos', max_length=20),
        ),
    ]
