# Generated by Django 4.2.13 on 2024-08-01 13:12

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_business_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='tax_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
        ),
    ]
