# Generated by Django 4.2.13 on 2024-08-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_business_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state_of_origin',
            field=models.CharField(default='Default', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state_of_residence',
            field=models.CharField(default='Default', max_length=20),
        ),
    ]
