# Generated by Django 4.2.13 on 2024-08-06 18:48

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customer_state_of_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='next_of_kin_name',
            field=models.CharField(default='Default', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_of_kin_phone',
            field=django_cryptography.fields.encrypt(models.CharField(default='Default', max_length=15, unique=True)),
        ),
    ]
