# Generated by Django 4.2.13 on 2024-08-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customer_address_customer_city_customer_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
    ]
