# Generated by Django 4.2.13 on 2024-08-12 11:32

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_business_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='next_of_kin_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='next_of_kin_phone',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=15, null=True, unique=True)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state_of_origin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state_of_residence',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
