# Generated by Django 4.2.13 on 2024-08-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customer_next_of_kin_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='-', max_length=40),
            preserve_default=False,
        ),
    ]
