# Generated by Django 4.2.13 on 2024-09-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customer_full_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/'),
        ),
    ]
