# Generated by Django 4.2.13 on 2026-01-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_business_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_legacy_user',
            field=models.BooleanField(default=False, help_text='User migrated from legacy system'),
        ),
    ]
