# Generated by Django 4.2.13 on 2026-01-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='risk_profile',
            field=models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('BALANCED', 'Balanced'), ('AGGRESIVE', 'Aggresive')], default='BALANCED', max_length=20),
        ),
    ]
