# Generated by Django 4.2.13 on 2024-08-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(db_index=True, max_length=4)),
                ('bank_name', models.CharField(max_length=30)),
            ],
        ),
    ]
