# Generated by Django 4.2.13 on 2024-08-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_code',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='wallet.bank'),
        ),
    ]
