# Generated by Django 4.2.13 on 2024-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_bankaccount_bank_code_bankaccount_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
