# Generated by Django 4.2.13 on 2024-08-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_bank_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='id',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_id',
            field=models.CharField(blank=True, default='', primary_key=True, serialize=False),
        ),
    ]
