# Generated by Django 4.2.13 on 2024-09-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_transaction_tx_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_entity',
            field=models.CharField(choices=[('WALLET', 'Wallet'), ('PLAN', 'Plan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_entity',
            field=models.CharField(choices=[('WALLET', 'Wallet'), ('PLAN', 'Plan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('INVESTMENT', 'Investment'), ('RETURN', 'Return'), ('TRANSFER', 'Transfer')], max_length=20),
        ),
    ]
