# Generated by Django 4.2.13 on 2024-08-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_business_tax_id_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_return_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=20)),
                ('contribution_frequency', models.CharField(max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('early_withdrawal_penalty', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goal_bonus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='UserSavingsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('savings_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.savingsplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('user_savings_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.usersavingsplan')),
            ],
        ),
    ]
