# Generated by Django 4.2.13 on 2026-01-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavingsplan',
            name='auto_transfer_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic recurring transfers'),
        ),
        migrations.AddField(
            model_name='usersavingsplan',
            name='failed_transfer_count',
            field=models.IntegerField(default=0, help_text='Consecutive failed transfer attempts'),
        ),
        migrations.AddField(
            model_name='usersavingsplan',
            name='last_transfer_date',
            field=models.DateTimeField(blank=True, help_text='Last successful auto-transfer date', null=True),
        ),
        migrations.AddField(
            model_name='usersavingsplan',
            name='transfer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to transfer automatically', max_digits=10, null=True),
        ),
    ]
