# Generated by Django 4.2.13 on 2024-08-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='expected_return_rate',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='max_investment',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='min_investment',
        ),
        migrations.RemoveField(
            model_name='savingsplan',
            name='max_contribution',
        ),
        migrations.RemoveField(
            model_name='savingsplan',
            name='min_contribution',
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='min_units',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
