# Generated by Django 4.2.13 on 2024-08-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_transfers_alter_campaign_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transfers',
            new_name='Transfer',
        ),
    ]
