# Generated by Django 4.2.13 on 2024-08-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_savingsplan_tier_alter_usersavingsplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavingsplan',
            name='savings_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_savings', to='campaigns.savingsplan'),
        ),
    ]
