# Generated by Django 4.2.13 on 2024-08-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_usersavingsplan_savings_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsplan',
            name='tier',
            field=models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('BALANCED', 'Balanced'), ('AGGRESIVE', 'Aggressive')], db_index=True, max_length=20),
        ),
    ]
