# Generated by Django 4.2.13 on 2024-08-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_savingsplan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='current_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersavingsplan',
            name='units_bought',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='risk_level',
            field=models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('BALANCED', 'Balanced'), ('AGGRESIVE', 'Aggressive')], max_length=12),
        ),
        migrations.AlterField(
            model_name='savingsplan',
            name='tier',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
