# Generated by Django 4.2.13 on 2024-08-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_campaign_current_units_campaign_total_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='max_units',
        ),
        migrations.AddField(
            model_name='usersavingsplan',
            name='title',
            field=models.CharField(db_index=True, default='Test Plan', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersavingsplan',
            name='savings_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_savings', to='campaigns.savingsplan'),
        ),
        migrations.AlterField(
            model_name='usersavingsplan',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
