# Generated by Django 4.2.13 on 2024-08-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_remove_campaign_max_units_usersavingsplan_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavingsplan',
            name='title',
            field=models.CharField(),
        ),
    ]
