# Generated by Django 4.2.13 on 2024-09-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='CampaignImages',
        ),
    ]
